// FUN_00ebd064 @ 00ebd064

/* WARNING: Restarted to delay deadcode elimination for space: ram */

void FUN_00ebd064(void)

{
  undefined *puVar1;
  undefined *puVar2;
  cfstringStruct *local_488;
  cfstringStruct *local_480;
  cfstringStruct *local_478;
  cfstringStruct *local_470;
  cfstringStruct *local_468;
  cfstringStruct *local_460;
  cfstringStruct *local_458;
  cfstringStruct *local_450;
  cfstringStruct *local_448;
  cfstringStruct *local_440;
  cfstringStruct *local_438;
  cfstringStruct *local_430;
  cfstringStruct *local_428;
  cfstringStruct *local_420;
  cfstringStruct *local_418;
  cfstringStruct *local_410;
  cfstringStruct *local_408;
  cfstringStruct *local_400;
  cfstringStruct *local_3f8;
  cfstringStruct *local_3f0;
  cfstringStruct *local_3e8;
  cfstringStruct *local_3e0;
  cfstringStruct *local_3d8;
  cfstringStruct *local_3d0;
  cfstringStruct *local_3c8;
  cfstringStruct *local_3c0;
  cfstringStruct *local_3b8;
  cfstringStruct *local_3b0;
  cfstringStruct *local_3a8;
  cfstringStruct *local_3a0;
  cfstringStruct *local_398;
  cfstringStruct *local_390;
  cfstringStruct *local_388;
  cfstringStruct *local_380;
  cfstringStruct *local_378;
  cfstringStruct *local_370;
  cfstringStruct *local_368;
  cfstringStruct *local_360;
  cfstringStruct *local_358;
  cfstringStruct *local_350;
  cfstringStruct *local_348;
  cfstringStruct *local_340;
  cfstringStruct *local_338;
  cfstringStruct *local_330;
  cfstringStruct *local_328;
  cfstringStruct *local_320;
  cfstringStruct *local_318;
  cfstringStruct *local_310;
  cfstringStruct *local_308;
  cfstringStruct *local_300;
  cfstringStruct *local_2f8;
  cfstringStruct *local_2f0;
  cfstringStruct *local_2e8;
  cfstringStruct *local_2e0;
  cfstringStruct *local_2d8;
  cfstringStruct *local_2d0;
  cfstringStruct *local_2c8;
  cfstringStruct *local_2c0;
  cfstringStruct *local_2b8;
  cfstringStruct *local_2b0;
  cfstringStruct *local_2a8;
  cfstringStruct *local_2a0;
  cfstringStruct *local_298;
  cfstringStruct *local_290;
  cfstringStruct *local_288;
  cfstringStruct *local_280;
  cfstringStruct *local_278;
  cfstringStruct *local_270;
  cfstringStruct *local_268;
  cfstringStruct *local_260;
  cfstringStruct *local_258;
  cfstringStruct *local_250;
  cfstringStruct *local_248;
  cfstringStruct *local_240;
  cfstringStruct *local_238;
  cfstringStruct *local_230;
  cfstringStruct *local_228;
  cfstringStruct *local_220;
  cfstringStruct *local_218;
  cfstringStruct *local_210;
  cfstringStruct *local_208;
  cfstringStruct *local_200;
  cfstringStruct *local_1f8;
  cfstringStruct *local_1f0;
  cfstringStruct *local_1e8;
  cfstringStruct *local_1e0;
  cfstringStruct *local_1d8;
  cfstringStruct *local_1d0;
  cfstringStruct *local_1c8;
  cfstringStruct *local_1c0;
  cfstringStruct *local_1b8;
  cfstringStruct *local_1b0;
  cfstringStruct *local_1a8;
  cfstringStruct *local_1a0;
  cfstringStruct *local_198;
  cfstringStruct *local_190;
  cfstringStruct *local_188;
  cfstringStruct *local_180;
  cfstringStruct *local_178;
  cfstringStruct *local_170;
  cfstringStruct *local_168;
  cfstringStruct *local_160;
  cfstringStruct *local_158;
  cfstringStruct *local_150;
  cfstringStruct *local_148;
  cfstringStruct *local_140;
  cfstringStruct *local_138;
  cfstringStruct *local_130;
  cfstringStruct *local_128;
  cfstringStruct *local_120;
  cfstringStruct *local_118;
  cfstringStruct *local_110;
  cfstringStruct *local_108;
  cfstringStruct *local_100;
  cfstringStruct *local_f8;
  cfstringStruct *local_f0;
  cfstringStruct *local_e8;
  cfstringStruct *local_e0;
  cfstringStruct *local_d8;
  cfstringStruct *local_d0;
  cfstringStruct *local_c8;
  cfstringStruct *local_c0;
  cfstringStruct *local_b8;
  cfstringStruct *local_b0;
  cfstringStruct *local_a8;
  cfstringStruct *local_a0;
  cfstringStruct *local_98;
  cfstringStruct *local_90;
  cfstringStruct *local_88;
  cfstringStruct *local_80;
  cfstringStruct *local_78;
  cfstringStruct *local_70;
  long local_68;
  
  local_68 = *(long *)PTR____stack_chk_guard_02578670;
  local_1d8 = &cf_multi_voip;
  local_120 = &cf_icons_filled_video_phone;
  local_1d0 = &cf_video_voip;
  local_118 = &cf_icons_filled_videocall;
  local_1c8 = &cf_voice_voip;
  local_110 = &cf_call_on_filled;
  local_1c0 = &cf_location;
  local_108 = &cf_location_filled;
  local_1b8 = &cf_location_real_time;
  local_100 = &cf_location_filled;
  local_1b0 = &cf_hong_bao;
  local_f8 = &cf_icons_filled_red_envelope;
  local_1a8 = &cf_sendGift;
  local_f0 = &cf_gift_filled_icon;
  local_1a0 = &cf_transfer_money;
  local_e8 = &cf_transfer_filled;
  local_198 = &cf_xiaowei;
  local_e0 = &cf_ai_filled;
  local_190 = &cf_voice_input;
  local_d8 = &cf_icons_filled_voiceinput_white;
  local_188 = &cf_finder;
  local_d0 = &cf_icons_outlined_finder;
  local_180 = &cf_favorite;
  local_c8 = &cf_favorites_filled;
  local_178 = &cf_chatroomtool;
  local_c0 = &cf_icons_filled_grouptool;
  local_170 = &cf_solitaireEntry;
  local_b8 = &cf_icon_outlined_solitaire;
  local_168 = &cf_roomLiveEntry;
  local_b0 = &cf_icons_filled_live;
  local_160 = &cf_share_card;
  local_a8 = &cf_person_filled;
  local_158 = &cf_file;
  local_a0 = &cf_folder_filled;
  local_150 = &cf_ka_quan;
  local_98 = &cf_cardholder_filled;
  local_148 = &cf_enterprise_brand;
  local_90 = &cf_icon_filled_enterprise_app;
  local_140 = &cf_musicSearch;
  local_88 = &cf_icon_music_filled;
  local_138 = &cf_wcr_attach_plugin_voice_pack;
  local_80 = &cf_icons_filled_song;
  local_130 = &cf_wcr_attach_plugin_small_signal;
  local_78 = &cf_bell_on_filled;
  local_128 = &cf_wcr_attach_toolbar_wcr_builtin_attachment_manage;
  local_70 = &cf_icons_filled_wrench;
  puVar2 = PTR__OBJC_CLASS___NSDictionary_026ce090;
  (*(code *)PTR__objc_msgSend_02578628)
            (PTR__OBJC_CLASS___NSDictionary_026ce090,PTR_s_dictionaryWithObjects_forKeys_co_0269d528
             ,&local_120,&local_1d8,0x17);
  _objc_retainAutoreleasedReturnValue();
  puVar1 = DAT_028e29e8;
  DAT_028e29e8 = puVar2;
  (*(code *)PTR__objc_release_02578630)(puVar1);
  local_328 = &cf_id_1;
  local_280 = &cf_picture_filled;
  local_320 = &cf_id_2;
  local_278 = &cf_camera_filled;
  local_318 = &cf_id_3;
  local_270 = &cf_icons_filled_video_phone;
  local_310 = &cf_id_4;
  local_268 = &cf_icons_filled_videocall;
  local_308 = &cf_id_5;
  local_260 = &cf_call_on_filled;
  local_300 = &cf_id_6;
  local_258 = &cf_location_filled;
  local_2f8 = &cf_id_7;
  local_250 = &cf_icons_filled_red_envelope;
  local_2f0 = &cf_id_1001;
  local_248 = &cf_gift_filled_icon;
  local_2e8 = &cf_id_8;
  local_240 = &cf_transfer_filled;
  local_2e0 = &cf_id_20;
  local_238 = &cf_ai_filled;
  local_2d8 = &cf_id_9;
  local_230 = &cf_icons_filled_voiceinput_white;
  local_2d0 = &cf_id_31;
  local_228 = &cf_icons_outlined_finder;
  local_2c8 = &cf_id_10;
  local_220 = &cf_favorites_filled;
  local_2c0 = &cf_id_11;
  local_218 = &cf_icons_filled_grouptool;
  local_2b8 = &cf_id_19;
  local_210 = &cf_icon_outlined_solitaire;
  local_2b0 = &cf_id_13;
  local_208 = &cf_icons_filled_live;
  local_2a8 = &cf_id_14;
  local_200 = &cf_person_filled;
  local_2a0 = &cf_id_15;
  local_1f8 = &cf_folder_filled;
  local_298 = &cf_id_16;
  local_1f0 = &cf_cardholder_filled;
  local_290 = &cf_id_12;
  local_1e8 = &cf_icon_filled_enterprise_app;
  local_288 = &cf_id_17;
  local_1e0 = &cf_icon_music_filled;
  puVar2 = PTR__OBJC_CLASS___NSDictionary_026ce090;
  (*(code *)PTR__objc_msgSend_02578628)
            (PTR__OBJC_CLASS___NSDictionary_026ce090,PTR_s_dictionaryWithObjects_forKeys_co_0269d528
             ,&local_280,&local_328,0x15);
  _objc_retainAutoreleasedReturnValue();
  puVar1 = DAT_028e29f0;
  DAT_028e29f0 = puVar2;
  (*(code *)PTR__objc_release_02578630)(puVar1);
  local_488 = &cf_gqGr;
  local_3d8 = &cf_picture_filled;
  local_480 = &cf_bDd;
  local_3d0 = &cf_camera_filled;
  local_478 = &cf_format_s_;
  local_3c8 = &cf_icons_filled_videocall;
  local_470 = &cf_format_s_;
  local_3c0 = &cf_call_on_filled;
  local_468 = &cf_YN;
  local_3b8 = &cf_icons_filled_video_phone;
  local_460 = &cf_MOn_;
  local_3b0 = &cf_location_filled;
  local_458 = &cf__eMOn_;
  local_3a8 = &cf_location_filled;
  local_450 = &cf__S;
  local_3a0 = &cf_icons_filled_red_envelope;
  local_448 = &cf_<yir;
  local_398 = &cf_gift_filled_icon;
  local_440 = &cf_l_;
  local_390 = &cf_transfer_filled;
  local_438 = &cf___;
  local_388 = &cf_ai_filled;
  local_430 = &cf_eQ;
  local_380 = &cf_icons_filled_voiceinput_white;
  local_428 = &cf_S;
  local_378 = &cf_icons_outlined_finder;
  local_420 = &cf_6e;
  local_370 = &cf_favorites_filled;
  local_418 = &cf___wQ;
  local_368 = &cf_icons_filled_grouptool;
  local_410 = &cf_c;
  local_360 = &cf_icon_outlined_solitaire;
  local_408 = &cf_vd;
  local_358 = &cf_icons_filled_live;
  local_400 = &cf__NNTGr;
  local_350 = &cf_person_filled;
  local_3f8 = &cf_TGr;
  local_348 = &cf_person_filled;
  local_3f0 = &cf_eN;
  local_340 = &cf_folder_filled;
  local_3e8 = &cf_aS8R;
  local_338 = &cf_cardholder_filled;
  local_3e0 = &cf_PN;
  local_330 = &cf_icon_music_filled;
  puVar2 = PTR__OBJC_CLASS___NSDictionary_026ce090;
  (*(code *)PTR__objc_msgSend_02578628)
            (PTR__OBJC_CLASS___NSDictionary_026ce090,PTR_s_dictionaryWithObjects_forKeys_co_0269d528
             ,&local_3d8,&local_488,0x16);
  _objc_retainAutoreleasedReturnValue();
  puVar1 = DAT_028e29f8;
  DAT_028e29f8 = puVar2;
  (*(code *)PTR__objc_release_02578630)(puVar1);
  if (*(long *)PTR____stack_chk_guard_02578670 - local_68 != 0) {
                    /* WARNING: Subroutine does not return */
    ___stack_chk_fail(*(long *)PTR____stack_chk_guard_02578670 - local_68);
  }
  return;
}

