// FUN_017ade98 @ 017ade98

void FUN_017ade98(void)

{
  undefined8 uVar1;
  undefined *puVar2;
  undefined *puVar3;
  cfstringStruct *local_2a0;
  cfstringStruct *local_298;
  cfstringStruct *local_290;
  cfstringStruct *local_288;
  cfstringStruct *local_280;
  cfstringStruct *local_278;
  cfstringStruct *local_270;
  cfstringStruct *local_268;
  cfstringStruct *local_260;
  cfstringStruct *local_258;
  cfstringStruct *local_250;
  cfstringStruct *local_248;
  cfstringStruct *local_240;
  cfstringStruct *local_238;
  cfstringStruct *local_230;
  cfstringStruct *local_228;
  cfstringStruct *local_220;
  cfstringStruct *local_218;
  cfstringStruct *local_210;
  cfstringStruct *local_208;
  cfstringStruct *local_200;
  cfstringStruct *local_1f8;
  cfstringStruct *local_1f0;
  cfstringStruct *local_1e8;
  cfstringStruct *local_1e0;
  cfstringStruct *local_1d8;
  cfstringStruct *local_1d0;
  cfstringStruct *local_1c8;
  cfstringStruct *local_1c0;
  cfstringStruct *local_1b8;
  cfstringStruct *local_1b0;
  cfstringStruct *local_1a8;
  cfstringStruct *local_1a0;
  cfstringStruct *local_198;
  cfstringStruct *local_190;
  cfstringStruct *local_188;
  cfstringStruct *local_180;
  cfstringStruct *local_178;
  cfstringStruct *local_170;
  cfstringStruct *local_168;
  cfstringStruct *local_160;
  cfstringStruct *local_158;
  cfstringStruct *local_150;
  cfstringStruct *local_148;
  cfstringStruct *local_140;
  cfstringStruct *local_138;
  cfstringStruct *local_130;
  cfstringStruct *local_128;
  cfstringStruct *local_120;
  cfstringStruct *local_118;
  cfstringStruct *local_110;
  cfstringStruct *local_108;
  cfstringStruct *local_100;
  cfstringStruct *local_f8;
  cfstringStruct *local_f0;
  cfstringStruct *local_e8;
  cfstringStruct *local_e0;
  cfstringStruct *local_d8;
  cfstringStruct *local_d0;
  cfstringStruct *local_c8;
  cfstringStruct *local_c0;
  cfstringStruct *local_b8;
  cfstringStruct *local_b0;
  cfstringStruct *local_a8;
  cfstringStruct *local_a0;
  cfstringStruct *local_98;
  cfstringStruct *local_90;
  cfstringStruct *local_88;
  cfstringStruct *local_80;
  cfstringStruct *local_78;
  cfstringStruct *local_70;
  cfstringStruct *local_68;
  cfstringStruct *local_60;
  cfstringStruct *local_58;
  cfstringStruct *local_50;
  cfstringStruct *local_48;
  cfstringStruct *local_40;
  cfstringStruct *local_38;
  cfstringStruct *local_30;
  long local_28;
  
  puVar3 = PTR__OBJC_CLASS___NSSet_026ce150;
  local_28 = *(long *)PTR____stack_chk_guard_02578670;
  local_2a0 = &cf_AccountDetailViewController;
  local_298 = &cf_WCRefineSuperFloatSettingsViewController;
  local_290 = &cf_WCRefineSuperFloatProfilesViewController;
  local_288 = &cf_WCRefineSuperFloatActionPickerViewController;
  local_280 = &cf_WCRefineSuperFloatBallWarehouseViewController;
  local_278 = &cf_WCRefineSuperFloatFanSettingsViewController;
  local_270 = &cf_WCRefineSuperFloatURLSchemeViewController;
  local_268 = &cf_LogViewerViewController;
  local_260 = &cf_NavigationMonitorViewController;
  local_258 = &cf_RepeatEnhanceViewController;
  local_250 = &cf_RepeatThemeIconSelectorViewController;
  local_248 = &cf_RX77ThemeRedeemViewController;
  local_240 = &cf_SpecificPageLockViewController;
  local_238 = &cf_ThemeBoxAirDropConsumedCodesDetailViewController;
  local_230 = &cf_ThemeBoxAirDropConsumedViewController;
  local_228 = &cf_ThemeBoxAirDropLogViewController;
  local_220 = &cf_ThemeBoxAirDropThemePickViewController;
  local_218 = &cf_ThemeBoxAirDropViewController;
  local_210 = &cf_ThemeBoxAutoRedeemViewController;
  local_208 = &cf_ThemeBoxRedeemViewController;
  local_200 = &cf_ThemeDetailViewController;
  local_1f8 = &cf_ThemeExchangeViewController;
  local_1f0 = &cf_ThemeProRedeemViewController;
  local_1e8 = &cf_WCRefineActionMenuViewController;
  local_1e0 = &cf_WCRefineAssistFunctionViewController;
  local_1d8 = &cf_WCRefineAvatarCornerBeautifyViewController;
  local_1d0 = &cf_WCRefineAvatarFrameLibraryViewController;
  local_1c8 = &cf_WCRefineBottomBarLongPressActionSelectorViewController;
  local_1c0 = &cf_WCRefineBottomBarOptionsViewController;
  local_1b8 = &cf_WCRefineChatAttachmentBeautifyViewController;
  local_1b0 = &cf_WCRefineChatAvatarProfileCardViewController;
  local_1a8 = &cf_WCRefineChatTimeViewController;
  local_1a0 = &cf_WCRefineColorPickerController;
  local_198 = &cf_WCRefineCornerViewController;
  local_190 = &cf_WCRefineFloatingTabBarButtonActionViewController;
  local_188 = &cf_WCRefineFloatingTabBarSettingsViewController;
  local_180 = &cf_WCRefineGeneralFunctionViewController;
  local_178 = &cf_WCRefineVoiceFunctionViewController;
  local_170 = &cf_WCRefineGlobalCornerSettingsViewController;
  local_168 = &cf_WCRefineKeywordAlertHistoryViewController;
  local_160 = &cf_WCRefineKeywordAlertHistoryCardViewController;
  local_158 = &cf_WCRefineKeywordAlertKeywordsViewController;
  local_150 = &cf_WCRefineKeywordAlertViewController;
  local_148 = &cf_WCRefineLayoutFunctionViewController;
  local_140 = &cf_WCRefineMenuBeautifyViewController;
  local_138 = &cf_WCRefineMessageBannerBeautifyViewController;
  local_130 = &cf_WCRefineMessageRepositoryViewController;
  local_128 = &cf_WCRefineMomentsDraftListViewController;
  local_120 = &cf_WCRefineMomentsViewController;
  local_118 = &cf_WCRefineMultiSelectGroupsViewController;
  local_110 = &cf_WCRefineMusicCoverViewController;
  local_108 = &cf_WCRefineNavigationAvatarViewController;
  local_100 = &cf_WCRefinePluginFeatureManagementViewController;
  local_f8 = &cf_WCRefinePluginManagementViewController;
  local_f0 = &cf_WCRefinePluginSortViewController;
  local_e8 = &cf_WCRefinePluginTopViewController;
  local_e0 = &cf_WCRefineProfileCardActionConfigViewController;
  local_d8 = &cf_WCRefineProfileCardBeautifyViewController;
  local_d0 = &cf_WCRefineProfileBgRegularRepositoryViewController;
  local_c8 = &cf_WCRefineProfileBgHTMLRepositoryViewController;
  local_c0 = &cf_WCRefineProfileBgURLHistoryViewController;
  local_b8 = &cf_WCRefineProfileCardFunctionPageViewController;
  local_b0 = &cf_WCRefinePush2ChatSettingViewController;
  local_a8 = &cf_WCRefineRedEnvelopViewController;
  local_a0 = &cf_WCRefineScreenshotFrameEditorViewController;
  local_98 = &cf_WCRefineScreenshotFrameLibraryViewController;
  local_90 = &cf_WCRefineSearchSettingsViewController;
  local_88 = &cf_WCRefineTextReplaceViewController;
  local_80 = &cf_WCRefineTopBarElementsViewController;
  local_78 = &cf_WCRefineTouchTrailViewController;
  local_70 = &cf_WCRefineSvgColorSchemeHistoryViewController;
  local_68 = &cf_WCRefineChatSinkHistoryViewController;
  local_60 = &cf_WCRefineUIBeautifyViewController;
  local_58 = &cf_WCRefineUICleanViewController;
  local_50 = &cf_WCRefineVersionController;
  local_48 = &cf_WCRefineWatermarkEditorViewController;
  local_40 = &cf_WCRefineWatermarkLibraryViewController;
  local_38 = &cf_WCRCommonFriendListViewController;
  local_30 = &cf_WCRCommonGroupListViewController;
  puVar2 = PTR__OBJC_CLASS___NSArray_026cdfe0;
  (*(code *)PTR__objc_msgSend_02578628)
            (PTR__OBJC_CLASS___NSArray_026cdfe0,PTR_s_arrayWithObjects_count__0269cc70,&local_2a0,
             0x4f);
  _objc_retainAutoreleasedReturnValue();
  (*(code *)PTR__objc_msgSend_02578628)(puVar3,PTR_s_setWithArray__0269d9a0);
  _objc_retainAutoreleasedReturnValue();
  uVar1 = DAT_028e41b8;
  DAT_028e41b8 = puVar3;
  (*(code *)PTR__objc_release_02578630)(uVar1);
  (*(code *)PTR__objc_release_02578630)(puVar2);
  if (*(long *)PTR____stack_chk_guard_02578670 - local_28 != 0) {
                    /* WARNING: Subroutine does not return */
    ___stack_chk_fail(*(long *)PTR____stack_chk_guard_02578670 - local_28);
  }
  return;
}

